# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # This will run the workflow every 20 minutes
    - cron: '*/20 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: Create credentials.json
      run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Check for required secrets
      if: env.EMAIL_USER == '' || env.EMAIL_PASS == ''
      run: |
        echo "Error: EMAIL_USER or EMAIL_PASS secret is not set."
        echo "Please configure them in your repository's Settings > Secrets and variables > Actions."
        exit 1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run main script
      run: python Agendator.py

