name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    # This will run the workflow every 20 minutes
    - cron: '*/20 * * * *'
  # Permite o disparo manual para testes
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file from secret
      # Este passo cria o arquivo .env usando o conteúdo do secret 'ENV'
      # O seu script Python irá carregar estas variáveis usando load_dotenv()
      run: echo "${{ secrets.ENV }}" > .env

    - name: Create credentials.json
      run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run main script
      run: python AgendatorActions.py





